site_name: 'Binary Ninja User Documentation'
site_url: 'https://docs.binary.ninja/'
repo_url: 'https://github.com/vector35/binaryninja-api'
repo_name: 'github'
site_description: 'Documentation for the Binary Ninja reverse engineering platform'
site_author: 'Vector 35 Inc'
google_analytics: ['UA-72420552-3', 'docs.binary.ninja' ]
use_directory_urls: False
extra_css: ['docs.css', 'github.min.css', 'juxtapose.css']
extra_javascript: ['highlight.min.js', 'cpp.min.js', 'python.min.js', 'juxtapose.js']
theme:
    name: material
    favicon: 'img/favicon.ico'
    highlightjs: true
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 191   # ? / /
    navigation_depth: 3
    palette:
      accent: deep orange
      primay: red

    copyright: '(<a href="https://creativecommons.org/licenses/by/3.0/">cc</a>) <a href="https://vector35.com/">Vector 35 Inc</a>'

plugins:
    - search

markdown_extensions:
    - codehilite
    - admonition
    - toc:
        permalink: True

nav:
    - Home: 'index.md'
    - Getting Started Guide: 'getting-started.md'
    - User Guide:
        - Plugins: 'guide/plugins.md'
        - Types: 'guide/type.md'
        - Debugger (Beta): 'guide/debugger.md'
        - Troubleshooting: 'guide/troubleshooting.md'
    - Developer Guide:
        - API: 'dev/api.md'
        - Python Plugins: 'dev/plugins.md'
        - Batch / Headless Automation: 'dev/batch.md'
        - BNIL Guide&#58; Overview: 'dev/bnil-overview.md'
        - BNIL Guide&#58; LLIL: 'dev/bnil-llil.md'
        - BNIL Guide&#58; MLIL: 'dev/bnil-mlil.md'
        - Flag Guide: 'dev/flags.md'
        - Creating Themes: 'dev/themes.md'
        - Contributing Documentation: 'dev/documentation.md'
    - About:
        - License: 'about/license.md'
        - Open Source: 'about/open-source.md'

extra:
    disablesearch: True
    logo: 'images/logo.png'
